### ISSUE TITLE
Dangerous change in scripts.tpl

### ISSUE THREAD

**Issue by SvenBrunk** [FACT-Finder-Web-Components/oxid-eshop-module#107]
Hello :)

I wanted to warn you about the change you did in scripts.tpl in commit 67863237bb20122260251f7a31da2d1b8359c77f
(In the meantime you even added some more usages on top)
The oConfig variable used here is available in any eShop in default configuration, but it depends on the performance setting to load languages to be active.
If this is not active, the variable does not exist and several shop pages cease to function.

I can mitigate that in our project and I would also question this dependency towards our development department, but nonetheless I wanted to warn you about it.

**Comment by SvenBrunk** [comment]
Addition: This variable was completely removed from that place in Wave Theme version 2.0.0
Please feed the variables you need from your controller.

**Comment by a-laurowski** [comment]
hi @SvenBrunk 
Is adding such a line an option?
`
  [{if !isset($oConfig)}]
     [{assign var="oConfig" value=$oViewConf->getConfig()}]
  [{/if}]
`
We are doing the same assignment couple of times in code already.
* https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/d47b63dd42dc11a99f4ba59e30b4b87cb0b5815e/src/views/frontend/blocks/campaign/cart.tpl#L1
* https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/master/src/views/frontend/blocks/search/result.tpl#L3 
* https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/master/src/views/frontend/blocks/category/list.tpl#L1
* https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/d47b63dd42dc11a99f4ba59e30b4b87cb0b5815e/src/views/frontend/blocks/category/sidebar.tpl#L1

**Comment by a-laurowski** [comment]
hi @SvenBrunk the PR is merged now. Feel free to reopen this ticket if necessary
