### ISSUE TITLE
beta version

### ISSUE THREAD

**Issue by ghost** [FACT-Finder-Web-Components/oxid-eshop-module#2]
hello

is this a beta release for factfinder?

**Comment by toarm** [comment]
Hi @sologics ,
we are currently in the process of releasing the `Community Edition` support (The module in its current state).

The Front-End part is very unlikely to change in the near future but the `Data Export Part` to FACT-Finder (Generating the csv file) might change as soon as we add the `Enterprise Edition Support`. 

Expect major changes in the `Data Export Part to` as soon as we start/finish the `Enterprise Edition` support. 

We will do the last review and acceptance tests for the `Community Edition` support  in the week of 07.10 - 11.10 so its very likely that we are going to release it end of octover offically.

fyi
@fmarangi @a-laurowski

**Comment by toarm** [comment]
@sologics you can take a look at the current module at https://oxid-esales.fact-finder.de
Here is a list of the final todos:
- check Feature flags for templates
- oxlocator für back to search
- Controller ID ff-namespace
- remvoe deprecated getViewName function
- chg visibility internal fields
- fix wrong Availability-field
- chg backend field names
- possibility to rename exported attributes
- AB price for master articel> oxvarmin

Looks like quite a bunch but none of these tasks is a major change

**Comment by toarm** [comment]
reopened for documentation purposes until v1 is released

**Comment by fmarangi** [comment]
v1.0 is out, closing this.
