### ISSUE TITLE
error if 3th-party module function is used / wrong class extension

### ISSUE THREAD

**Issue by tabsl** [FACT-Finder-Web-Components/oxid-eshop-module#39]
hi guys,

this is not the way to extend an oxid class ;-) https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/master/src/Export/Data/ExportArticle.php

please see oxid docu for more information: https://docs.oxid-esales.com/developer/en/6.0/modules/good_practices/extend_shop_class.html

this extension doesn´t work if a function from an other oxid module is used, eg.:

`Function 'sxGetAttributeValue' does not exist or is not accessible! (Omikron\FactFinder\Oxid\Export\Data\ExportArticle)`

regards

**Comment by fmarangi** [comment]
Hmm, I see ... will try to find another way to filter the collection. If you have any ideas feel free to post it here :-)

**Comment by fmarangi** [comment]
@tabsl I think it's solved now, would you like to have a look at it?

**Comment by rahsm** [comment]
@fmarangi @tabsl looks good to me, the error is gone now
