### ISSUE TITLE
The module is missing some configurable parameter, e.g. for currency formatting of custom fields

### ISSUE THREAD

**Issue by SvenBrunk** [FACT-Finder-Web-Components/oxid-eshop-module#77]
Not all parameters from https://web-components.fact-finder.de/api/4.x/ff-communication#tab=api that make sense are configurable via the module settings.
Either those should be added or at least be added to the 
    protected $mergeableParams = ['add-params', 'add-tracking-params', 'keep-url-params', 'parameter-whitelist'];

so they can be configured via the "Additional Parameters" field.

**Comment by paulfcdd** [comment]
We are currently have plans to add multi currency export to the FACT-Finder feed export and we will stay in touch with You about this issue

**Comment by SvenBrunk** [comment]
Depending on how long this will take you, the proposed pull request would make it possible for us to mitigate the issue until you have a final solution.

**Comment by SvenBrunk** [comment]
Ignore my last comment :) Wie made the above change as composer patch. So we can work without that for the moment
