### ISSUE TITLE
New version tag needed

### ISSUE THREAD

**Issue by SvenBrunk** [FACT-Finder-Web-Components/oxid-eshop-module#78]
We need this line for the module to correctly talk to our shiny new FACT-Finder backend. Else the links within a landing page do not work and the DevConsole of the browser will only show an error message from the web components JavaScript that tracking campaigns does not work (BTW: It is good to throw an error in the console, but it is not good to prevent the links from functioning if the data-redirect-target is _self ... )

https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/2816fe265458ffef728b4bf54e6cd6517ad94a76/src/Model/Config/Communication.php#L38

So please, can we have a new release soon? :)

**Comment by a-laurowski** [comment]
Hi @SvenBrunk 
The new [v2.0.1](https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/releases/tag/v2.0.1) has just been released

**Comment by SvenBrunk** [comment]
Thank you very much!
