### ISSUE TITLE
ff/ffwebcomponents/views/frontend/page/result.tpl path wrong or works as intended

### ISSUE THREAD

**Issue by FKrohmer** [FACT-Finder-Web-Components/oxid-eshop-module#99]
I think this should also changed to from `page/factfinder/result.tpl` to `ff/page/result.tpl` to be more consistens. Or is it works as intended?  
It is just a bit confusing.

https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/fab320bd54499bf6e092b842a54c0f7b71761592/src/metadata.php#L104

**Comment by a-laurowski** [comment]
Hi @FKrohmer  and thanks for report.
I think in assumption it was to distinct that file from others as it was holding a layout for whole page.
I agree that it might be placed in `ff` directory to make the file structure more self-consistent.
We will move that file in next major release as such an operation should be treated as breaking change

**Comment by a-laurowski** [comment]
I will keep this issue opened for the time being to make sure it will be taken into account once releasing new major version

**Comment by FKrohmer** [comment]
I think the `search.tpl` is missing in this list, too. Or I´m wrong? Maybe some more?
```php
'ff/search.tpl'                   => 'ff/ffwebcomponents/views/frontend/widget/search.tpl',
```

**Comment by a-laurowski** [comment]
it is used in block extension definition
https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/fab320bd54499bf6e092b842a54c0f7b71761592/src/metadata.php#L91

**Comment by FKrohmer** [comment]
thank for the fast response! I simply overlooked.
